language: node_js
node_js:
  - "7.7.x"
install:
  - npm install
script:
  - gulp locales
  - gulp dev
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: 'build'
    github_token: $GITHUB_TOKEN
    on:
      branch: master
